app:
  jwtSecret: ${JWT_SECRET}

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: posts
          uri: http://posts:8082
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - name: JwtAuthenticationFilter
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true